### ISSUE TITLE
Question: Treat empty strings in `params` for `execute`

### ISSUE THREAD

**Issue by realjanpaulus** [snapADDY/databank#11]
When I want to insert into a table with `execute_many()` I can use multiple params. But sometimes it is possible that values of a dictionary contain empty strings which can't be inserted. The solution is to change them to `None`. 

```python
insert_queries = QueryCollection.from_file("src/queries/insert.sql")

album_params = [{
        "artist_name": "HVOB",
        "album_name": "HVOB",
        "album_release_date": "",
        "album_type": "Album",
        "album_genre": ""
    },]
db.execute_many(insert_queries["insert_album"], album_params)
```

My question is: Is there maybe a solution planned to automatically convert empty strings to `None` or is the expected solution here to convert the empty strings to `None` by the user?

**Comment by severinsimmler** [comment]
I'd say it is expected that `""` stays `""` and `None` stays `None` (i.e. user has take care of it if not), because there is also a semantic difference (also in SQL) between an empty string and `None` (or `NULL`).

Assume:
```sql
CREATE TABLE foo (bar TEXT NOT NULL);
```

You might want to be able to insert an empty string into `bar`, but not `NULL`.
